id: I63234400
legacy_id: P000338
ocr_import_info:
  bdrc_scan_id: W1GS44552
  source: bdrc
  ocr_info:
    timestamp: '2020-03-13T19:20:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T02:21:31.044134+00:00'
last_modified: 2022-08-27 10:21:38.478773
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS44552
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS44552
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟི་ལིང་བཀྲ་ཤིས་གླིང་ཀའི་བྱང་ཆུབ་མཆོད་རྟེན་ཆེན་མོ་གསར་བཞེངས་ཀྱི་དཀར་ཆག
statistics:
  ocr_word_mean_confidence_index: 0.9056912099915813
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1GS44556:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS44556
      total_pages: 33
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS44556.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9056912099915813
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
