id: I63234400
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T19:20:16+00:00'
last_modified: '2022-06-15T16:41:55.713037+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS44552
  title: ཟི་ལིང་བཀྲ་ཤིས་གླིང་ཀའི་བྱང་ཆུབ་མཆོད་རྟེན་ཆེན་མོ་གསར་བཞེངས་ཀྱི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    89A8:
      image_group_id: I1GS44556
      title: Volume 1 of zi ling bkra shis gling ka'i byang chub mchod rten chen mo
        gsar bzhengs kyi dkar chag
      total_pages: 33
      order: 1
      base_file: 89A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
